# PREGUNTAS
#CALL sp_insertarPregunta(titulo(varchar),valor(int),ayuda(varchar));
CALL sp_insertarPregunta("¿Comúnmente con cuantas personas viajaría?","Sin incluirse a usted mismo");
CALL sp_insertarPregunta("¿Cuáles serían sus necesidades con respecto a la cajuela o maletero?","La cajuela o maletero es el compartimiento de un vehiculo destinado a guardar el equipaje Nnormalmente ubicado en el lado opuesto al del motor");
CALL sp_insertarPregunta("¿Considera importante que su automóvil sea llamativo visualmente incorporando materiales y acabados premium?","Se define como material premium a aquellos como la piel o cuero, aluminio, entre otros");
CALL sp_insertarPregunta("¿Qué piensa del equipamiento orientado a facilitar o hacer más cómoda la conducción?"," (control de crucero, asistente de ascenso en pendientes,  climatizador, etc.)");
CALL sp_insertarPregunta("¿Qué piensa del equipamiento tecnológico orientado al info-entretenimiento dentro de su automóvil?","El infoentretenimiento es todo haspecto ");
CALL sp_insertarPregunta("¿Qué opina acerca de los elementos y sistemas orientados a la seguridad de un automóvil?","En este campo entran conceptos como bolsas de aire, tipo y tecnología de frenos, cinturones de seguridad, sistemas inteligentes, etc");
CALL sp_insertarPregunta("¿Es probable o piensa viajar de manera frecuente con bebés o niños pequeños?","");
CALL sp_insertarPregunta("¿Tiene contemplado el viajar frecuentemente con alguna persona con limitaciones físicas o de capacidades diferentes?","Una discapacidad es una falta o limitación de alguna facultad física o mental que imposibilita o dificulta el desarrollo normal de la actividad de una persona");
CALL sp_insertarPregunta("¿Que opción describe mejor los trayectos que en su mayoría recorre de manera habitual?","");
CALL sp_insertarPregunta("¿Qué tan frecuentes son las pendientes en los trayectos que recorre de manera habitual?","");
CALL sp_insertarPregunta("¿Tiende a realizar con frecuencia viajes largos (de más de 100km) en donde contempla el uso de un automóvil?","");
CALL sp_insertarPregunta("Para usted un automóvil es:","Seleccione la opción más acertada");
CALL sp_insertarPregunta("¿Con frecuencia suele visitar lugares nuevos o entornos muy variados?","");
CALL sp_insertarPregunta("¿Tiene alguna preferencia por el tipo de transmisión?","Ej. Visitar multiples puntos de una ciudad a lo largo del día o lasemana");
CALL sp_insertarPregunta("Contemplando un día de uso normal. ¿Aproximadamente cuanto tiempo pasaría manejando un automóvil?","contemplando sus actividades normales");
CALL sp_insertarPregunta("¿Que aspecto valora mas de un automóvil?","seleccione la mas relevante para usted");
CALL sp_insertarPregunta("¿Cuánto dinero estaría dispuesto a pagar por un automóvil nuevo?","monto aproximado");

# RESPUESTAS
#CALL sp_insertarRespuesta(titulo(varchar),valor(int),idpregunta(INT));
CALL sp_insertarRespuesta("Solo yo o con una persona más",1);
CALL sp_insertarRespuesta("Con 3 o hasta 4 personas más",1);
CALL sp_insertarRespuesta("Con 5 o más personas",1);
CALL sp_insertarRespuesta("Con un maletero pequeño lo veo suficiente",2);
CALL sp_insertarRespuesta("Veo indispensable un maletero amplio",2);
CALL sp_insertarRespuesta("Necesitaría mas espacio del que me ofrece un maletero común ya que frecuentemente transporto objetos de gran peso y volumen",2);
CALL sp_insertarRespuesta("Si, no me importaría pagar un poco más por tener mejores materiales de fabricación y acabados",3);
CALL sp_insertarRespuesta("No, me interesan más otros aspectos",3);
CALL sp_insertarRespuesta("Mientras más elementos tecnológicos de este tipo, mejor",4);
CALL sp_insertarRespuesta("Me gustaría equipamiento tecnológico moderado que me permita una cómoda conducción sin prodigar demasiado en este aspecto",4);
CALL sp_insertarRespuesta("Prefiero limitarme a las características básicas que un auto ofrece en este aspecto y priorizar otros",4);
CALL sp_insertarRespuesta("Me interesa todo tipo de equipamiento tecnológico que un auto pueda ofrecerme para tener una experiencia más confortable",5);
CALL sp_insertarRespuesta("Aprecio un equipamiento tecnológico moderado que me permita disfrutar la música, y mantenerme en comunicación de manera segura",5);
CALL sp_insertarRespuesta("Prefiero una conducción más tranquila con opción a disfrutar solo de música, y darle mas prioridad a otro tipo de aspectos",5);
CALL sp_insertarRespuesta("Para mi es lo mas importante de un automóvil , y prefiero no escatimar",6);
CALL sp_insertarRespuesta("Lo considero importante, pero no es un aspecto determinante",6);
CALL sp_insertarRespuesta("Me basta con los elementos básicos de seguridad que un auto pueda ofrecer",6);
CALL sp_insertarRespuesta("Sí",7);
CALL sp_insertarRespuesta("No",7);
CALL sp_insertarRespuesta("Sí",8);
CALL sp_insertarRespuesta("No",8);
CALL sp_insertarRespuesta("Vialidades con múltiples topes / reductores de velocidad / semáforos / baches",9);
CALL sp_insertarRespuesta("Vialidades con pocos topes /reductores de velocidad / semáforos",9);
CALL sp_insertarRespuesta("Caminos difíciles o terrenos Off-Road",9);
CALL sp_insertarRespuesta("Muy frecuentes",10);
CALL sp_insertarRespuesta("Medianamente frecuentes",10);
CALL sp_insertarRespuesta("Muy poco frecuentes",10);
CALL sp_insertarRespuesta("Sí",11);
CALL sp_insertarRespuesta("No",11);
CALL sp_insertarRespuesta("Un medio para facilitarme el día a día y disminuir gastos",12);
CALL sp_insertarRespuesta("Un medio indispensable para cumplir mis labores y me es importante su buen desempeño",12);
CALL sp_insertarRespuesta("Un lujo o gusto personal que me permita salir sólo o con amigos",12);
CALL sp_insertarRespuesta("Muy frecuentemente",13);
CALL sp_insertarRespuesta("Un par de veces al mes",13);
CALL sp_insertarRespuesta("Muy poco o casi nunca",13);
CALL sp_insertarRespuesta("No",14);
CALL sp_insertarRespuesta("Transmisión Manual",14);
CALL sp_insertarRespuesta("Transmisión Automática",14);
CALL sp_insertarRespuesta("1 hora o menos",15);
CALL sp_insertarRespuesta("Entre 1 y 3 horas",15);
CALL sp_insertarRespuesta("3 horas o más",15);
CALL sp_insertarRespuesta("Su capacidad de velocidad y control",16);
CALL sp_insertarRespuesta("Su capacidad de eficiencia energética y ahorro",16);
CALL sp_insertarRespuesta("Otra",16);
CALL sp_insertarRespuesta("De preferencia menos de 220,000 pesos",17);
CALL sp_insertarRespuesta("Entre 220,000 y 350,000 pesos",17);
CALL sp_insertarRespuesta("Entre 350,000 y 500,000 pesos",17);
CALL sp_insertarRespuesta("Entre 500,000 y 1,500,000 pesos",17);

